name: Deploy to AWS S3

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the "main" branch

jobs:
  deploy:
    name: Deploy to S3 Bucket
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy to S3
      - name: Deploy to S3 bucket
        run: |
          aws s3 sync . arn:aws:s3:::rewonka-deploytest --delete
